
server:
  port: 8091
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/publiccode?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource